### PR TITLE
Add further public holidays for moldova...

### LINKED ISSUE #217: Wrong DescriptionPropertiesKey for Easter and Easter Monday for Moldova.
`EASTER` and `EASTER_MONDAY` entries in `Holidays_md.xml` configuration file were missing `descriptionPropertiesKey` property.

### PR DESCRIPTION
**Pull request by derTobsch**
* International woman day on March 8th
* Chrildrens day on June 1st
* Christmas on December 25th

closes #217

### CODE REVIEW

**Comment by mfedkowicz** [comment]
Oh, I've added the tests as well (as requested yesterday) ;) (https://github.com/focus-shift/jollyday/pull/219)

Regarding these added holidays I'm not 100% sure either cause I'm from Poland and I have no direct contact to Moldova end users. I will try to check, though and get back to you.

One thing to notice is that probably Children's day is no more a national holiday, but it was up until 2021 (source: https://www.officeholidays.com/holidays/moldova/international-childrens-day)

**Comment by mfedkowicz** [comment]
ok, as to my best knowledge all the days you've added are indeed public holidays in Moldova.

Children's Day is public holiday since 2016 (source: https://gov.md/en/content/government-declared-international-childrens-day-day)

**Comment by derTobsch** [comment]
Thanks for the tests! I had some time and wanted to learn more about the public holidays in Moldova and started some tests :D The `validFrom`s are nice. I will take your pr and will look what my will add to it.

Thanks for your work!

**Comment by mfedkowicz** [comment]
Hi @derTobsch,

thank you for quickly merging the pull requests :) One more question - would you be able to release last changes regarding Moldova soon? I'd be happy to update jollyday version in my project :)

**Comment by derTobsch** [comment]
> Hi @derTobsch,
> 
> thank you for quickly merging the pull requests :) One more question - would you be able to release last changes regarding Moldova soon? I'd be happy to update jollyday version in my project :)

Release is on its way.

**Pull request merged**
