### PR TITLE
 🎁 Add "dia da consciência negra" - new national holiday in Brazil

### PR DESCRIPTION
**Pull request by paulovitorbal**
Added the holiday November 20, valid from 2024 - valid in all cities and states in Brazil.

# Security Vulnerabilities
It's not related to any security vulnerability.

# Describing Your Changes

Added a new holiday into the Brazil's calendar: `jollyday-core/src/main/resources/holidays/Holidays_br.xml`
This new holiday was introduced in December, 21, 2023. By the national lay 13.759/23 available at: [Government official page](https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/l14759.htm)

### CODE REVIEW

**Comment by paulovitorbal** [comment]
Please let me know if you need anything else from me. 

Glad to help!

**Comment by paulovitorbal** [comment]
@derTobsch, 

Vielen Dank! Thanks for your time.

**Comment by paulovitorbal** [comment]
I will update the translation files accordingly.

Until last year (2023) many cities and states had this date as local holliday. In some places it was called `Zumbi's day`. And in others it was called `Black Awareness Day`. The official name is `Dia Nacional de Zumbi e da Consciência Negra` that can be translated as `National day of Zumbi and black awareness`. 

The law I mentioned earlier is valid in all cities and states by now, but it does not exclude any municipal or state law that creates a local holiday. So for some cities/states you may have two holidays in the same date with different names. And that's just the chaos of Brazil's law system.

And just to give a bit more of context, Zumbi was the last leader of the Palmares quilombo (a community made of slaves that managed to escape from their enslavers). Palmares was the biggest quilombo. He was killed by the government orders at November, 20th.

So given all that context, what do you think is the more appropriate name for this holiday?

I will make the adjustments as soon as possible.

Thanks.

**Comment by derTobsch** [comment]
> I will update the translation files accordingly.
> 
> Until last year (2023) many cities and states had this date as local holliday. In some places it was called `Zumbi's day`. And in others it was called `Black Awareness Day`. The official name is `Dia Nacional de Zumbi e da Consciência Negra` that can be translated as `National day of Zumbi and black awareness`.

Lets take this `Dia Nacional de Zumbi e da Consciência Negra` or in english `National day of Zumbi and black awareness`.

> 
> The law I mentioned earlier is valid in all cities and states by now, but it does not exclude any municipal or state law that creates a local holiday. So for some cities/states you may have two holidays in the same date with different names. And that's just the chaos of Brazil's law system.
> 
> And just to give a bit more of context, Zumbi was the last leader of the Palmares quilombo (a community made of slaves that managed to escape from their enslavers). Palmares was the biggest quilombo. He was killed by the government orders at November, 20th.
> 
> So given all that context, what do you think is the more appropriate name for this holiday?
> 
> I will make the adjustments as soon as possible.
> 
> Thanks.

Thanks for all the information!

**Comment by paulovitorbal** [comment]
@derTobsch,

I did the translations using deepl. But I am not sure if deepl understood that Zumbi is a person name and not the noum translation to English.

Please let me know if I need to change anything else. 

I am very glad to help.

**Comment by derTobsch** [comment]
Hey @paulovitorbal,

thanks for your work. Yes the translations are, in my opinion, not correct. What if we use these?

| Language     | Translation                                              |
|--------------|----------------------------------------------------------|
| German       | Nationaler Tag von Zumbi und schwarzem Bewusstsein       |
| Greek        | Εθνική Ημέρα του Ζουμπί και της Μαύρης Συνείδησης        |
| French       | Journée nationale de Zumbi et de la conscience noire     |
| Dutch        | Nationale dag van Zumbi en zwarte bewustwording          |
| Portuguese   | Dia Nacional de Zumbi e da Consciência Negra             |
| Swedish      | Nationella dagen för Zumbi och svart medvetenhet         |

**Comment by paulovitorbal** [comment]
Sure, I will update the PR accordingly.

**Comment by derTobsch** [comment]
Thanks for your work @paulovitorbal. I will merge it and adjust the translations on main

**Pull request merged**
